### ISSUE TITLE
JEI interface bugs

### ISSUE THREAD

**Issue by MrRedstoneToGo** [rekales/create-linked-activator#4]
1. The width of JEI'S interface (indexes)  does not adjust when opening a Linked Remote:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e37c6f8f-5471-4bef-97b8-6d8035bbbf19" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c0f045df-c068-4787-9ad9-83ad9aad7c88" />

2. You cannot pull items from the JEI index (or favorites) into the frequency

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/8f01d575-28ba-48a2-b0bd-8a67cfdc790a" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/1590932d-f6e4-43c8-b588-6d66df3e88f5" />

**Comment by rekales** [comment]
fixed for 1.1.0 and posted.
thanks for the report.

**Comment by BugInYourCode01** [comment]
Hi, you still cannot drag items from the JEI index into the controller gui.
Otherwise, well done.

**Comment by rekales** [comment]
Ah, right. Well I'll have this issue open until i add it.
This will take a while since I'll have to finagle with JEI plugins so I'll leave it to be done in a later version.

**Comment by rekales** [comment]
Added the item dragging feature in a recent commit, will publish later.
